<?php

return [
    [
        'id' => 'mission_pickup_one_phrase',
        'category' => 'conversation_entry',
        'skill_tag' => '共感返し',
        'title' => '今日のミッション',
        'action_text' => '相手の言葉を1回拾って返す',
        'success_hint' => '相手の最後の一言を短く繰り返してから返すと自然です。',
        'difficulty' => 1,
        'recommended_for_types' => ['flow_leader', 'energy_booster'],
        'avoid_if_recent_days' => 2,
    ],
    [
        'id' => 'mission_preemptive_refill',
        'category' => 'air_reading',
        'skill_tag' => '先回り行動',
        'title' => '今日のミッション',
        'action_text' => 'おかわりを1回先回りで聞く',
        'success_hint' => 'グラスが空になる少し前に声をかけるのがコツです。',
        'difficulty' => 1,
        'recommended_for_types' => ['flow_leader', 'silent_analyzer', 'all_rounder'],
        'avoid_if_recent_days' => 2,
    ],
    [
        'id' => 'mission_leave_one_impression',
        'category' => 'closing',
        'skill_tag' => '締めの一言',
        'title' => '今日のミッション',
        'action_text' => '最後に印象に残る一言を1回入れる',
        'success_hint' => '短くていいので、その人に合う一言を残すのがポイントです。',
        'difficulty' => 2,
        'recommended_for_types' => ['soft_healer', 'calm_empath', 'silent_analyzer'],
        'avoid_if_recent_days' => 3,
    ],
    [
        'id' => 'mission_soft_first_smile',
        'category' => 'conversation_entry',
        'skill_tag' => '入りの笑顔',
        'title' => '今日のミッション',
        'action_text' => '席についた最初にやわらかい笑顔を意識する',
        'success_hint' => '最初の3秒だけ意識するだけでも印象が変わります。',
        'difficulty' => 1,
        'recommended_for_types' => ['soft_healer', 'calm_empath', 'elegant_calm'],
        'avoid_if_recent_days' => 2,
    ],
    [
        'id' => 'mission_add_special_word',
        'category' => 'appearance_strategy',
        'skill_tag' => '特別感演出',
        'title' => '今日のミッション',
        'action_text' => '少しだけ特別感のある言い方を1回入れる',
        'success_hint' => 'やりすぎず、軽く入れるのがコツです。',
        'difficulty' => 2,
        'recommended_for_types' => ['sweet_spark', 'soft_healer'],
        'avoid_if_recent_days' => 3,
    ],
    [
        'id' => 'mission_keep_posture',
        'category' => 'basic_manners',
        'skill_tag' => '姿勢',
        'title' => '今日のミッション',
        'action_text' => '会話中に1回、姿勢を整えることを意識する',
        'success_hint' => '少し前傾で聞くだけで印象がかなり良くなります。',
        'difficulty' => 1,
        'recommended_for_types' => ['elegant_calm', 'all_rounder', 'energy_booster'],
        'avoid_if_recent_days' => 2,
    ],
    [
        'id' => 'mission_observe_then_move',
        'category' => 'air_reading',
        'skill_tag' => '観察から行動へ',
        'title' => '今日のミッション',
        'action_text' => '気づいたことを1回行動に変える',
        'success_hint' => '灰皿・飲み物・表情のどれかに気づいたら動いてみましょう。',
        'difficulty' => 2,
        'recommended_for_types' => ['silent_analyzer', 'calm_empath'],
        'avoid_if_recent_days' => 2,
    ],
    [
        'id' => 'mission_energy_with_politeness',
        'category' => 'service_behavior',
        'skill_tag' => '丁寧な盛り上げ',
        'title' => '今日のミッション',
        'action_text' => '盛り上げながらも一言丁寧さを足す',
        'success_hint' => '元気さのあとに「ありがとうございます」を入れるだけでも変わります。',
        'difficulty' => 2,
        'recommended_for_types' => ['energy_booster', 'flow_leader'],
        'avoid_if_recent_days' => 3,
    ],
    [
        'id' => 'mission_name_once',
        'category' => 'conversation_entry',
        'skill_tag' => '名前呼び',
        'title' => '今日のミッション',
        'action_text' => '会話の中で相手の名前を1回呼ぶ',
        'success_hint' => '不自然に連発せず、ここぞというタイミングで1回入れると自然です。',
        'difficulty' => 1,
        'recommended_for_types' => ['calm_empath', 'soft_healer', 'all_rounder'],
        'avoid_if_recent_days' => 2,
    ],
    [
        'id' => 'mission_one_natural_compliment',
        'category' => 'conversation_entry',
        'skill_tag' => '自然な褒め',
        'title' => '今日のミッション',
        'action_text' => '自然な褒め言葉を1回入れる',
        'success_hint' => '見た目だけでなく、話し方や雰囲気を褒めると自然です。',
        'difficulty' => 1,
        'recommended_for_types' => ['sweet_spark', 'energy_booster', 'all_rounder'],
        'avoid_if_recent_days' => 2,
    ],
    [
        'id' => 'mission_open_with_light_topic',
        'category' => 'conversation_entry',
        'skill_tag' => '会話スタート',
        'title' => '今日のミッション',
        'action_text' => '最初に軽い話題を1つ出して空気を作る',
        'success_hint' => '天気・来店タイミング・飲み物など軽い話題から入ると自然です。',
        'difficulty' => 1,
        'recommended_for_types' => ['flow_leader', 'energy_booster', 'silent_analyzer'],
        'avoid_if_recent_days' => 2,
    ],
    [
        'id' => 'mission_ashtray_before_request',
        'category' => 'basic_manners',
        'skill_tag' => '灰皿交換',
        'title' => '今日のミッション',
        'action_text' => '灰皿交換を1回先に気づいて行う',
        'success_hint' => '吸い殻が2〜3本たまったら、自然な一言を添えて交換してみましょう。',
        'difficulty' => 1,
        'recommended_for_types' => ['silent_analyzer', 'elegant_calm', 'flow_leader'],
        'avoid_if_recent_days' => 2,
    ],
    [
        'id' => 'mission_two_handed_glass',
        'category' => 'basic_manners',
        'skill_tag' => 'グラス所作',
        'title' => '今日のミッション',
        'action_text' => 'グラスを1回だけ丁寧に両手で扱うことを意識する',
        'success_hint' => '渡す・受ける・置くのどれか1回だけでも丁寧さを見せると印象が上がります。',
        'difficulty' => 1,
        'recommended_for_types' => ['elegant_calm', 'calm_empath', 'all_rounder'],
        'avoid_if_recent_days' => 2,
    ],
    [
        'id' => 'mission_adjust_distance_once',
        'category' => 'service_behavior',
        'skill_tag' => '距離感調整',
        'title' => '今日のミッション',
        'action_text' => '相手の反応を見て距離感を1回調整する',
        'success_hint' => '近づくでも離れるでもOKです。相手に合わせて調整することが大事です。',
        'difficulty' => 2,
        'recommended_for_types' => ['silent_analyzer', 'sweet_spark', 'soft_healer'],
        'avoid_if_recent_days' => 3,
    ],
    [
        'id' => 'mission_slow_down_movements',
        'category' => 'service_behavior',
        'skill_tag' => '動きの落ち着き',
        'title' => '今日のミッション',
        'action_text' => '席での動きをいつもより少しゆっくりにする',
        'success_hint' => '立つ・座る・グラスに触る、そのどれかを少し丁寧にするだけで変わります。',
        'difficulty' => 1,
        'recommended_for_types' => ['energy_booster', 'flow_leader', 'all_rounder'],
        'avoid_if_recent_days' => 2,
    ],
    [
        'id' => 'mission_allow_short_silence',
        'category' => 'silence',
        'skill_tag' => '沈黙対応',
        'title' => '今日のミッション',
        'action_text' => '沈黙をすぐ埋めず、2秒だけ様子を見る',
        'success_hint' => '焦って埋める前に、相手の表情や呼吸を見る意識を持つと落ち着きます。',
        'difficulty' => 2,
        'recommended_for_types' => ['soft_healer', 'calm_empath', 'silent_analyzer'],
        'avoid_if_recent_days' => 3,
    ],
    [
        'id' => 'mission_rescue_silence_with_small_topic',
        'category' => 'silence',
        'skill_tag' => '沈黙フォロー',
        'title' => '今日のミッション',
        'action_text' => '会話が止まったら小さい話題を1つ投げる',
        'success_hint' => '大きな話題より、その場のものや直前の会話から拾うと自然です。',
        'difficulty' => 2,
        'recommended_for_types' => ['flow_leader', 'energy_booster', 'all_rounder'],
        'avoid_if_recent_days' => 2,
    ],
    [
        'id' => 'mission_last_words_fit_person',
        'category' => 'closing',
        'skill_tag' => '締めの所作',
        'title' => '今日のミッション',
        'action_text' => '帰り際にその人に合う一言を1回残す',
        'success_hint' => '安心・印象・次回導線のどれを残すか、相手に合わせて選ぶのがコツです。',
        'difficulty' => 2,
        'recommended_for_types' => ['elegant_calm', 'soft_healer', 'sweet_spark'],
        'avoid_if_recent_days' => 3,
    ],
    [
        'id' => 'mission_invite_next_talk_naturally',
        'category' => 'nomination',
        'skill_tag' => '次回導線',
        'title' => '今日のミッション',
        'action_text' => '「また話したい」と自然に伝える一言を1回入れる',
        'success_hint' => '重くせず、会話の続きや安心感につなげる言い方が自然です。',
        'difficulty' => 2,
        'recommended_for_types' => ['soft_healer', 'calm_empath', 'sweet_spark'],
        'avoid_if_recent_days' => 3,
    ],
    [
        'id' => 'mission_match_makeup_to_theme',
        'category' => 'appearance_strategy',
        'skill_tag' => 'テーマ別メイク',
        'title' => '今日のミッション',
        'action_text' => '今日の接客テーマに合わせてメイクを1つ調整する',
        'success_hint' => '積極性なら目元、安心感なら柔らかさ、上品さならツヤ感を意識するとやりやすいです。',
        'difficulty' => 2,
        'recommended_for_types' => ['sweet_spark', 'energy_booster', 'elegant_calm', 'all_rounder'],
        'avoid_if_recent_days' => 3,
    ],
];
