<?php

return [
    [
        'id' => 'm1_ashtray_change',
        'category' => 'basic_manners',
        'category_label' => '基本マナー',
        'scene' => '灰皿に吸い殻が2〜3本溜まっている。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'B',
        'choices' => [
            [
                'key' => 'A',
                'text' => '何も言わずサッと交換する',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '手際は良いですが、一言あるとさらに印象が良くなります。',
            ],
            [
                'key' => 'B',
                'text' => '「灰皿お取り替えしますね」と一言添えて交換する',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。気遣いが言葉でも伝わる対応です。',
            ],
            [
                'key' => 'C',
                'text' => 'お客様が言うまで待つ',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '待ちすぎると気配り不足に見えやすいです。先回りできるとより良いです。',
            ],
            [
                'key' => 'D',
                'text' => '「汚れてきましたね」と言ってから交換する',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '交換は良いですが、汚れを直接言葉にしない方が上品に見えます。',
            ],
        ],
        'skill_tags' => ['気配り', '基本所作', '灰皿交換'],
    ],

    [
        'id' => 'm2_glass_serving',
        'category' => 'basic_manners',
        'category_label' => '基本マナー',
        'scene' => 'ドリンクをお客様の前に置く場面。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'C',
        'choices' => [
            [
                'key' => 'A',
                'text' => 'テーブルにそのまま置く',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '最低限ではありますが、印象を上げるには一言や目線があると良いです。',
            ],
            [
                'key' => 'B',
                'text' => '「どうぞ」と言いながら置く',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '良い対応です。声かけがあると接客感が出ます。',
            ],
            [
                'key' => 'C',
                'text' => '目を見て軽く会釈しながら置く',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。丁寧さと感じの良さが両方伝わります。',
            ],
            [
                'key' => 'D',
                'text' => 'テンポ重視で勢いよく置く',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '雑に見えやすいので注意です。丁寧さを優先すると印象が上がります。',
            ],
        ],
        'skill_tags' => ['ドリンク提供', '丁寧さ', '第一印象'],
    ],

    [
        'id' => 'm3_glass_holding',
        'category' => 'basic_manners',
        'category_label' => '基本マナー',
        'scene' => 'お客様にコップやグラスを手渡しする場面。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'B',
        'choices' => [
            [
                'key' => 'A',
                'text' => '片手で渡す',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '場面によっては問題ありませんが、丁寧さを出すならもう一歩です。',
            ],
            [
                'key' => 'B',
                'text' => '両手で丁寧に渡す',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。基本所作として安心感があります。',
            ],
            [
                'key' => 'C',
                'text' => '軽く持って自然に差し出す',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '自然で良いです。相手との距離感によっては好印象です。',
            ],
            [
                'key' => 'D',
                'text' => 'テーブルに置いて指で示す',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '少し雑に見えやすいです。手渡しや一言があると印象が上がります。',
            ],
        ],
        'skill_tags' => ['グラス所作', '丁寧さ', '基本マナー'],
    ],

    [
        'id' => 'm4_posture_listening',
        'category' => 'basic_manners',
        'category_label' => '基本マナー',
        'scene' => 'お客様の話を聞いているときの姿勢。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'A',
        'choices' => [
            [
                'key' => 'A',
                'text' => '少し前傾で、聞く姿勢を作る',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。興味と礼儀が両方伝わります。',
            ],
            [
                'key' => 'B',
                'text' => '背もたれに寄りかかりながら聞く',
                'rank' => 'good',
                'score' => 2,
                'feedback' => 'リラックス感はありますが、相手によっては少し軽く見えることがあります。',
            ],
            [
                'key' => 'C',
                'text' => '足を組んで話を聞く',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '場面によっては成立しますが、基本所作としてはややラフです。',
            ],
            [
                'key' => 'D',
                'text' => 'テーブルに肘をついて聞く',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => 'だらしなく見えやすいので避けた方が安全です。',
            ],
        ],
        'skill_tags' => ['姿勢', '聞き方', '基本所作'],
    ],

    [
        'id' => 's1_distance_control',
        'category' => 'service_behavior',
        'category_label' => '接客所作',
        'scene' => '席についた直後、どのくらいの距離で座るか迷っている。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'B',
        'choices' => [
            [
                'key' => 'A',
                'text' => '最初から少し近めに座る',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '相手によっては良いですが、初回では近すぎることがあります。',
            ],
            [
                'key' => 'B',
                'text' => '様子を見ながら距離を調整する',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。相手に合わせられるのが接客力です。',
            ],
            [
                'key' => 'C',
                'text' => '最初は少し距離を取り、反応を見て近づく',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '良い対応です。慎重で安心感があります。',
            ],
            [
                'key' => 'D',
                'text' => 'かなり離れて座る',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '距離が遠すぎると接客の熱量が伝わりにくくなります。',
            ],
        ],
        'skill_tags' => ['距離感', '初回接客', '観察力'],
    ],

    [
        'id' => 's2_entry_behavior',
        'category' => 'service_behavior',
        'category_label' => '接客所作',
        'scene' => '席についた直後、最初の動き方。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'B',
        'choices' => [
            [
                'key' => 'A',
                'text' => 'すぐに話しかける',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '勢いはありますが、相手の状態を一瞬見る余裕があるとさらに良いです。',
            ],
            [
                'key' => 'B',
                'text' => '軽く笑顔を見せて、相手の様子を見ながら入る',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。自然で入りやすい空気が作れます。',
            ],
            [
                'key' => 'C',
                'text' => '静かに座って相手からの反応を待つ',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '落ち着いてはいますが、少し受け身に見えることがあります。',
            ],
            [
                'key' => 'D',
                'text' => '手元やスマホに意識が向く',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '接客の立ち上がりとしては印象が下がりやすいです。',
            ],
        ],
        'skill_tags' => ['入り方', '第一印象', '笑顔'],
    ],

    [
        'id' => 's3_body_touch_timing',
        'category' => 'service_behavior',
        'category_label' => '接客所作',
        'scene' => '距離感を作る中で、自然な接触のタイミングを考える。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'A',
        'choices' => [
            [
                'key' => 'A',
                'text' => '自然な流れの中で軽く入れる',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。流れと相手の反応を見ているのが好印象です。',
            ],
            [
                'key' => 'B',
                'text' => '最初から積極的に距離を詰める',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '相手によっては早すぎます。初回では慎重さも大事です。',
            ],
            [
                'key' => 'C',
                'text' => '一切しない',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '安全ではあります。タイプによっては十分成立します。',
            ],
            [
                'key' => 'D',
                'text' => '話の流れと関係なく唐突に触れる',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '不自然さが強く出るので避けた方が良いです。',
            ],
        ],
        'skill_tags' => ['距離感', '接触タイミング', '空気読み'],
    ],

    [
        'id' => 's4_table_movement',
        'category' => 'service_behavior',
        'category_label' => '接客所作',
        'scene' => '席での動き方そのものが印象になる場面。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'A',
        'choices' => [
            [
                'key' => 'A',
                'text' => '落ち着いてゆっくり動く',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。余裕と安心感が伝わります。',
            ],
            [
                'key' => 'B',
                'text' => '少しテンポよく動く',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '悪くないです。元気さは出ますが、場面によっては少し忙しく見えます。',
            ],
            [
                'key' => 'C',
                'text' => 'ガサガサと動きが多い',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '落ち着きがなく見えやすいので改善余地があります。',
            ],
            [
                'key' => 'D',
                'text' => 'ほとんど動かない',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '静かさはありますが、存在感が薄くなることがあります。',
            ],
        ],
        'skill_tags' => ['所作', '落ち着き', '見え方'],
    ],

    [
        'id' => 't1_first_greeting',
        'category' => 'conversation_entry',
        'category_label' => '会話の入り',
        'scene' => '席について最初の一言をかける。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'B',
        'choices' => [
            [
                'key' => 'A',
                'text' => '「こんばんは」だけで入る',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '丁寧ですが、もう一歩だけ人柄が見えるとさらに良いです。',
            ],
            [
                'key' => 'B',
                'text' => '「初めまして、よろしくです」と軽く親しみを足す',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。丁寧さと話しやすさのバランスがあります。',
            ],
            [
                'key' => 'C',
                'text' => '「今日はどんな感じですか？」とすぐ質問する',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '悪くないですが、少し急ぎすぎに見えることがあります。',
            ],
            [
                'key' => 'D',
                'text' => '「何飲みます？」から入る',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '業務感が先に立ちやすいです。最初は人としての接触を優先すると良いです。',
            ],
        ],
        'skill_tags' => ['挨拶', '第一声', '第一印象'],
    ],

    [
        'id' => 't2_name_timing',
        'category' => 'conversation_entry',
        'category_label' => '会話の入り',
        'scene' => 'お客様の名前を聞くタイミング。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'B',
        'choices' => [
            [
                'key' => 'A',
                'text' => '席についてすぐ聞く',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '悪くないですが、相手によっては少し早く感じることがあります。',
            ],
            [
                'key' => 'B',
                'text' => '少し会話してから自然に聞く',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。距離感が自然です。',
            ],
            [
                'key' => 'C',
                'text' => '名前は聞かない',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '名前を呼べると距離感が縮まりやすいです。',
            ],
            [
                'key' => 'D',
                'text' => '最後の方で思い出したように聞く',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '遅すぎると接客の自然さが弱くなります。',
            ],
        ],
        'skill_tags' => ['名前呼び', '距離感', '会話導入'],
    ],

    [
        'id' => 't3_compliment_balance',
        'category' => 'conversation_entry',
        'category_label' => '会話の入り',
        'scene' => '最初の会話で褒める場面。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'A',
        'choices' => [
            [
                'key' => 'A',
                'text' => '自然に一つだけ褒める',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。自然で嫌味がありません。',
            ],
            [
                'key' => 'B',
                'text' => 'たくさん褒めて盛り上げる',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '場面によっては効きますが、やりすぎると軽く見えることがあります。',
            ],
            [
                'key' => 'C',
                'text' => '特に褒めずに進める',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '無難ではありますが、最初の印象作りは弱くなりやすいです。',
            ],
            [
                'key' => 'D',
                'text' => '不自然なくらい大げさに褒める',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => 'わざとらしさが出やすいので注意です。',
            ],
        ],
        'skill_tags' => ['褒め方', '会話導入', '印象形成'],
    ],

    [
        'id' => 't4_conversation_start',
        'category' => 'conversation_entry',
        'category_label' => '会話の入り',
        'scene' => '最初の会話の始め方を選ぶ。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'B',
        'choices' => [
            [
                'key' => 'A',
                'text' => 'いきなり質問から入る',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '悪くないですが、少し尋問っぽく感じる人もいます。',
            ],
            [
                'key' => 'B',
                'text' => '軽い雑談から入って、自然に会話を作る',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。入りやすく、空気もやわらぎます。',
            ],
            [
                'key' => 'C',
                'text' => '相手に任せる',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '受け身に見えやすいので、少しだけこちらから動けると良いです。',
            ],
            [
                'key' => 'D',
                'text' => '最初から深い話に入る',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '初回では重たく感じられやすいです。',
            ],
        ],
        'skill_tags' => ['会話スタート', '空気作り', '第一印象'],
    ],

    [
        'id' => 'a1_tired_customer_response',
        'category' => 'air_reading',
        'category_label' => '空気読み',
        'scene' => 'お客様が疲れている様子で席についている。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'B',
        'choices' => [
            [
                'key' => 'A',
                'text' => 'あえて静かにして様子を見る',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '落ち着きはありますが、一言あるとさらに安心感が出ます。',
            ],
            [
                'key' => 'B',
                'text' => 'やさしく声をかけて様子を聞く',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。気遣いが伝わりやすいです。',
            ],
            [
                'key' => 'C',
                'text' => 'とにかく明るく盛り上げる',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '人によっては助かりますが、疲れているときは強すぎることがあります。',
            ],
            [
                'key' => 'D',
                'text' => '特に触れず放置する',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '無関心に見えやすいです。',
            ],
        ],
        'skill_tags' => ['空気読み', '疲れ客対応', '気遣い'],
    ],

    [
        'id' => 'a2_high_tension_response',
        'category' => 'air_reading',
        'category_label' => '空気読み',
        'scene' => 'お客様がすでにかなり盛り上がっている。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'A',
        'choices' => [
            [
                'key' => 'A',
                'text' => '流れに合わせてさらに盛り上げる',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。相手の温度に合わせられています。',
            ],
            [
                'key' => 'B',
                'text' => 'まず観察して、入りどころを探す',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '慎重で良いです。流れを壊しにくい対応です。',
            ],
            [
                'key' => 'C',
                'text' => '少し落ち着かせようとする',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '場面によっては必要ですが、最初から温度を下げるとズレることがあります。',
            ],
            [
                'key' => 'D',
                'text' => '無反応で様子を見る',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '置いていかれやすく、存在感が薄くなります。',
            ],
        ],
        'skill_tags' => ['空気読み', '盛り上がり対応', '温度感'],
    ],

    [
        'id' => 'a3_silence_handling',
        'category' => 'air_reading',
        'category_label' => '空気読み',
        'scene' => '会話が止まり、少し沈黙が流れている。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'A',
        'choices' => [
            [
                'key' => 'A',
                'text' => '軽く話題を出して、流れを戻す',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。自然に場を前へ進められています。',
            ],
            [
                'key' => 'B',
                'text' => '少し様子を見てから動く',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '慎重で良いです。相手のタイプによっては正解です。',
            ],
            [
                'key' => 'C',
                'text' => 'スマホや手元に意識を逃がす',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '接客放棄っぽく見えるので避けたいです。',
            ],
            [
                'key' => 'D',
                'text' => '無理にたくさん話して埋める',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '気持ちは良いですが、焦りが見えることがあります。',
            ],
        ],
        'skill_tags' => ['沈黙対応', '空気読み', '会話調整'],
    ],

    [
        'id' => 'a4_refill_timing',
        'category' => 'air_reading',
        'category_label' => '空気読み',
        'scene' => 'おかわりや追加オーダーを勧めるタイミング。',
        'question' => 'この場面で、より良い接客はどれ？',
        'best_choice' => 'A',
        'choices' => [
            [
                'key' => 'A',
                'text' => 'グラスが空になりかけたタイミングで自然に聞く',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。先回り感があり、スマートです。',
            ],
            [
                'key' => 'B',
                'text' => '完全に空になってから聞く',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '悪くないですが、少し遅く見えることがあります。',
            ],
            [
                'key' => 'C',
                'text' => '言われるまで待つ',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '慎重ではありますが、気配りの印象は弱くなります。',
            ],
            [
                'key' => 'D',
                'text' => '特に気にしない',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '接客品質が下がって見えやすいです。',
            ],
        ],
        'skill_tags' => ['タイミング', '追加オーダー', '先回り'],
    ],

    [
        'id' => 'v1_active_makeup',
        'category' => 'appearance_strategy',
        'category_label' => '見た目戦略',
        'scene' => '今日は積極性を出したい日。見た目で印象を寄せたい。',
        'question' => 'この日に、より合いやすいのはどれ？',
        'best_choice' => 'B',
        'choices' => [
            [
                'key' => 'A',
                'text' => 'かなりナチュラルなメイクで行く',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '清潔感はありますが、積極性を見せたい日には少し控えめです。',
            ],
            [
                'key' => 'B',
                'text' => '少し強めのメイクで目元をはっきりさせる',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。積極性や存在感が出やすいです。',
            ],
            [
                'key' => 'C',
                'text' => 'いつも通りのメイクで行く',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '安定感はあります。大きく外しません。',
            ],
            [
                'key' => 'D',
                'text' => 'かなりラフにして印象を弱める',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '狙いと逆に見えやすいです。',
            ],
        ],
        'skill_tags' => ['メイク', '積極性', '印象戦略'],
    ],

    [
        'id' => 'v2_hairstyle_active',
        'category' => 'appearance_strategy',
        'category_label' => '見た目戦略',
        'scene' => '今日は少し華やかさと動きを出したい。',
        'question' => 'この日に、より合いやすいのはどれ？',
        'best_choice' => 'A',
        'choices' => [
            [
                'key' => 'A',
                'text' => 'ふんわり巻いて動きを出す',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。華やかさと柔らかさが出ます。',
            ],
            [
                'key' => 'B',
                'text' => 'ストレートで整える',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '清潔感はありますが、動きや印象の強さは少し弱めです。',
            ],
            [
                'key' => 'C',
                'text' => 'まとめ髪で上品に見せる',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '上品にまとまります。狙う印象次第ではかなり良いです。',
            ],
            [
                'key' => 'D',
                'text' => '無造作で整えきらずに行く',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => 'ラフすぎて接客の印象が下がりやすいです。',
            ],
        ],
        'skill_tags' => ['髪型', '華やかさ', '印象づくり'],
    ],

    [
        'id' => 'v3_impression_direction',
        'category' => 'appearance_strategy',
        'category_label' => '見た目戦略',
        'scene' => '今日の接客で、相手にどう見られたいかを考える。',
        'question' => 'より基本として安定しやすい方向はどれ？',
        'best_choice' => 'A',
        'choices' => [
            [
                'key' => 'A',
                'text' => '柔らかい印象を作る',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。幅広い客層に受け入れられやすい基本です。',
            ],
            [
                'key' => 'B',
                'text' => '明るく元気な印象を作る',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '良い方向です。場によってはかなり強い武器になります。',
            ],
            [
                'key' => 'C',
                'text' => 'クールで近寄りがたい印象を作る',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => 'ハマる客層はありますが、基本としては狭くなりやすいです。',
            ],
            [
                'key' => 'D',
                'text' => '特に方向性を決めずに行く',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '印象設計がないと接客の再現性が下がりやすいです。',
            ],
        ],
        'skill_tags' => ['印象設計', '見た目戦略', '方向性'],
    ],

    [
        'id' => 'v4_clothes_cleanliness',
        'category' => 'appearance_strategy',
        'category_label' => '見た目戦略',
        'scene' => '服の選び方で第一印象を整えたい。',
        'question' => '基本として、より良いのはどれ？',
        'best_choice' => 'A',
        'choices' => [
            [
                'key' => 'A',
                'text' => '清潔感を最優先して選ぶ',
                'rank' => 'best',
                'score' => 3,
                'feedback' => 'とても良いです。基本の印象は清潔感で大きく決まります。',
            ],
            [
                'key' => 'B',
                'text' => '露出を強めにして印象を作る',
                'rank' => 'good',
                'score' => 2,
                'feedback' => '狙いが合えば強いですが、土台の清潔感が前提です。',
            ],
            [
                'key' => 'C',
                'text' => '個性を優先して選ぶ',
                'rank' => 'ok',
                'score' => 1,
                'feedback' => '個性は武器ですが、基本の安心感が先にあるとより強いです。',
            ],
            [
                'key' => 'D',
                'text' => 'その日その場で適当に決める',
                'rank' => 'weak',
                'score' => 0,
                'feedback' => '見た目戦略がないと安定した印象を作りにくいです。',
            ],
        ],
        'skill_tags' => ['服装', '清潔感', '第一印象'],
    ],
];