CREATE TABLE IF NOT EXISTS cast_transport_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  store_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  pickup_zip VARCHAR(16) DEFAULT NULL,
  pickup_prefecture VARCHAR(64) DEFAULT NULL,
  pickup_city VARCHAR(128) DEFAULT NULL,
  pickup_address1 VARCHAR(255) DEFAULT NULL,
  pickup_address2 VARCHAR(255) DEFAULT NULL,
  pickup_building VARCHAR(255) DEFAULT NULL,
  pickup_note VARCHAR(255) DEFAULT NULL,
  pickup_lat DECIMAL(10,7) DEFAULT NULL,
  pickup_lng DECIMAL(10,7) DEFAULT NULL,
  pickup_geocoded_at DATETIME DEFAULT NULL,
  pickup_enabled TINYINT(1) NOT NULL DEFAULT 1,
  privacy_level VARCHAR(32) NOT NULL DEFAULT 'manager_only',
  created_by_user_id BIGINT UNSIGNED DEFAULT NULL,
  updated_by_user_id BIGINT UNSIGNED DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cast_transport_profiles_store_user (store_id, user_id),
  KEY idx_cast_transport_profiles_store_enabled (store_id, pickup_enabled),
  KEY idx_cast_transport_profiles_store_lat_lng (store_id, pickup_lat, pickup_lng)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS store_transport_bases (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  store_id BIGINT UNSIGNED NOT NULL,
  base_type VARCHAR(32) NOT NULL DEFAULT 'store',
  name VARCHAR(128) NOT NULL,
  address_text VARCHAR(255) DEFAULT NULL,
  lat DECIMAL(10,7) DEFAULT NULL,
  lng DECIMAL(10,7) DEFAULT NULL,
  is_default TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_store_transport_bases_store_default (store_id, is_default),
  KEY idx_store_transport_bases_store_type (store_id, base_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS transport_route_plans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  business_date DATE NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  direction VARCHAR(16) NOT NULL DEFAULT 'pickup',
  plan_status VARCHAR(16) NOT NULL DEFAULT 'draft',
  base_id BIGINT UNSIGNED DEFAULT NULL,
  target_arrival_time TIME DEFAULT NULL,
  vehicle_count INT NOT NULL DEFAULT 1,
  cast_count INT NOT NULL DEFAULT 0,
  total_distance_km DECIMAL(10,2) DEFAULT NULL,
  total_duration_min INT DEFAULT NULL,
  optimizer_version VARCHAR(64) DEFAULT NULL,
  optimizer_meta_json LONGTEXT DEFAULT NULL,
  created_by_user_id BIGINT UNSIGNED DEFAULT NULL,
  confirmed_by_user_id BIGINT UNSIGNED DEFAULT NULL,
  confirmed_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_transport_route_plans_store_date (store_id, business_date),
  KEY idx_transport_route_plans_status (plan_status, direction)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS transport_route_stops (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  route_plan_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  cast_user_id BIGINT UNSIGNED DEFAULT NULL,
  stop_order INT NOT NULL,
  stop_type VARCHAR(32) NOT NULL DEFAULT 'pickup',
  planned_at DATETIME DEFAULT NULL,
  travel_minutes_from_prev INT DEFAULT NULL,
  distance_km_from_prev DECIMAL(10,2) DEFAULT NULL,
  source_lat DECIMAL(10,7) DEFAULT NULL,
  source_lng DECIMAL(10,7) DEFAULT NULL,
  dest_lat DECIMAL(10,7) DEFAULT NULL,
  dest_lng DECIMAL(10,7) DEFAULT NULL,
  address_snapshot VARCHAR(255) DEFAULT NULL,
  note VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_transport_route_stops_route_order (route_plan_id, stop_order),
  KEY idx_transport_route_stops_route (route_plan_id),
  KEY idx_transport_route_stops_store_cast (store_id, cast_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS transport_route_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  business_date DATE NOT NULL,
  store_id BIGINT UNSIGNED DEFAULT NULL,
  direction VARCHAR(16) NOT NULL DEFAULT 'pickup',
  job_status VARCHAR(16) NOT NULL DEFAULT 'queued',
  requested_by_user_id BIGINT UNSIGNED DEFAULT NULL,
  request_payload_json LONGTEXT DEFAULT NULL,
  result_route_plan_id BIGINT UNSIGNED DEFAULT NULL,
  started_at DATETIME DEFAULT NULL,
  finished_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_transport_route_jobs_date_status (business_date, job_status),
  KEY idx_transport_route_jobs_store_direction (store_id, direction)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
