SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS fm_applicant_import_raw (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_key VARCHAR(64) NOT NULL,
  source_file VARCHAR(255) NULL,
  row_no INT UNSIGNED NOT NULL,
  process_status ENUM('pending','done','error','skipped') NOT NULL DEFAULT 'pending',
  processed_at DATETIME NULL,
  error_message TEXT NULL,
  legacy_record_no VARCHAR(100) NOT NULL,
  person_code VARCHAR(40) NULL,
  last_name VARCHAR(60) NULL,
  first_name VARCHAR(60) NULL,
  last_name_kana VARCHAR(60) NULL,
  first_name_kana VARCHAR(60) NULL,
  birth_date_text VARCHAR(40) NULL,
  phone VARCHAR(30) NULL,
  postal_code VARCHAR(20) NULL,
  current_address VARCHAR(255) NULL,
  previous_address VARCHAR(255) NULL,
  blood_type VARCHAR(10) NULL,
  body_height_cm VARCHAR(20) NULL,
  body_weight_kg VARCHAR(20) NULL,
  bust_cm VARCHAR(20) NULL,
  waist_cm VARCHAR(20) NULL,
  hip_cm VARCHAR(20) NULL,
  cup_size VARCHAR(10) NULL,
  shoe_size VARCHAR(20) NULL,
  clothing_top_size VARCHAR(20) NULL,
  clothing_bottom_size VARCHAR(20) NULL,
  photo_original_path VARCHAR(255) NULL,
  photo_file_name VARCHAR(255) NULL,
  photo_public_url VARCHAR(255) NULL,
  interview_date_text VARCHAR(40) NULL,
  interview_time_text VARCHAR(20) NULL,
  interview_store_code VARCHAR(30) NULL,
  interview_store_name VARCHAR(100) NULL,
  interviewer_login_id VARCHAR(50) NULL,
  interviewer_name VARCHAR(100) NULL,
  interview_result VARCHAR(30) NULL,
  application_route VARCHAR(100) NULL,
  recruitment_slot_note VARCHAR(255) NULL,
  interview_notes TEXT NULL,
  previous_job VARCHAR(120) NULL,
  desired_hourly_wage VARCHAR(30) NULL,
  desired_daily_wage VARCHAR(30) NULL,
  preferred_store_code VARCHAR(30) NULL,
  preferred_store_name VARCHAR(100) NULL,
  trial_status VARCHAR(30) NULL,
  trial_date_text VARCHAR(40) NULL,
  trial_feedback TEXT NULL,
  join_decision VARCHAR(30) NULL,
  join_date_text VARCHAR(40) NULL,
  next_action_note VARCHAR(255) NULL,
  genji_name VARCHAR(80) NULL,
  current_status VARCHAR(30) NULL,
  current_store_code VARCHAR(30) NULL,
  current_store_name VARCHAR(100) NULL,
  joined_at_text VARCHAR(40) NULL,
  moved_at_text VARCHAR(40) NULL,
  left_at_text VARCHAR(40) NULL,
  move_reason VARCHAR(255) NULL,
  leave_reason VARCHAR(255) NULL,
  appearance_score VARCHAR(10) NULL,
  communication_score VARCHAR(10) NULL,
  motivation_score VARCHAR(10) NULL,
  cleanliness_score VARCHAR(10) NULL,
  sales_potential_score VARCHAR(10) NULL,
  retention_potential_score VARCHAR(10) NULL,
  score_comment TEXT NULL,
  notes TEXT NULL,
  raw_json LONGTEXT NULL,
  imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_fm_applicant_import_batch_row (batch_key, row_no),
  KEY idx_fm_applicant_import_status (process_status, imported_at),
  KEY idx_fm_applicant_import_legacy (legacy_record_no),
  KEY idx_fm_applicant_import_batch (batch_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
